# Generated by Django 5.0.2 on 2024-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='default.jpeg', upload_to='images'),
        ),
    ]
