# Generated by Django 5.0.2 on 2024-03-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='content',
            field=models.TextField(default='Text Content'),
            preserve_default=False,
        ),
    ]
